@startuml
!theme plain


package "Data Processing Layer" {
  class Article_1new {
    + printArticle1New(): void
  }
 
  class ExpenseManager {
    {static} {final} - CATEGORIES : String[][]
    {static} {final} - AMOUNTS : long[][]
  
    + showCategories() : void
    + showExpenseDetails(codes : String...) : void
    + showExpenses() : void
    - findIndexByCode(code : String) : int
  }
  class RevenueManager {
    {static} {final} - CATEGORIES : String[][]
    {static} {final} - AMOUNTS : long[][]
  
    + showCategories() : void
    + showRevenueDetails(codes : String[]) : void
    - findIndexByCode(code : String) : int
    + showRevenues() : void
  }

  

}

' ========== ΚΥΡΙΕΣ ΣΧΕΣΕΙΣ ==========
Article_1new --> BudgetData : creates
BudgetRevenueReader --> RevenueRecord : creates

Article_1new --> RevenueManager : uses 
Article_1new --> ExpenseManager : uses